services:
  postgres:
    image: postgres:16-alpine
    container_name: junction-postgres
    environment:
      POSTGRES_USER: junction
      POSTGRES_PASSWORD: junction_password
      POSTGRES_DB: junction_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U junction -d junction_db"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    container_name: junction-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
volumes:
  postgres_data:
  redis_data: