-- General RLS
ALTER TABLE themes
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE listings
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE courses
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE sections
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE section_data
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE evaluations
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE prereqs
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE instructors
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE course_instructor_associations
  ENABLE ROW LEVEL SECURITY;